server:
  port: 8085

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wms_demo?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456

mybatis-plus:
  mapper-locations: classpath:/mapping/*.xml
  type-aliases-package: com.eshore.wms.pojo